Parameter:
    type: entity
    table: parameter
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        companyId:
            type: integer
            unsigned: false
            nullable: true
            column: company_id
        group:
            type: integer
            unsigned: false
            nullable: true
        position:
            type: integer
            unsigned: false
            nullable: true
        name:
            type: string
            length: 255
            fixed: false
            nullable: true
        isActive:
            type: boolean
            nullable: true
            column: is_active
    lifecycleCallbacks: {  }
