Paramgroup:
    type: entity
    table: paramgroup
    fields:
        id:
            id: true
            type: smallint
            nullable: false
            generator:
                strategy: IDENTITY
        companyId:
            type: integer
            unsigned: false
            nullable: true
            column: company_id
        type:
            type: boolean
            nullable: true
        position:
            type: smallint
            nullable: true
        name:
            type: string
            length: 32
            fixed: false
            nullable: true
        isActive:
            type: boolean
            nullable: true
            column: is_active
    lifecycleCallbacks: {  }
