Client:
    type: entity
    table: relation
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        parentId:
            type: integer
            unsigned: false
            nullable: false
            column: parent_id
        childId:
            type: integer
            unsigned: false
            nullable: false
            column: child_id
        type:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
