Utilityprovider:
    type: entity
    table: utilityprovider
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        value:
            type: string
            length: 60
            fixed: false
            nullable: true
        type:
            type: integer
            unsigned: false
            nullable: false
    manyToOne:
        client:
            targetEntity: Client
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                client_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
