UtilityproviderId:
    type: entity
    table: utilityprovider_id
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        value:
            type: string
            length: 60
            fixed: false
            nullable: true
    manyToOne:
        person:
            targetEntity: Person
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                person_id:
                    referencedColumnName: id
            orphanRemoval: false
        utilityprovider:
            targetEntity: Utilityprovider
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                utilityprovider_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
