Utilityprovider:
    type: entity
    table: utilityprovider
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        clientId:
            type: integer
            unsigned: false
            nullable: false
            column: client_id
        type:
            type: smallint
            nullable: true
        value:
            type: string
            length: 60
            fixed: false
            nullable: true
    lifecycleCallbacks: {  }
